'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Provider } from 'react-redux'
import {store} from './Store/page'
import { BrowserRouter } from 'react-router-dom';
import { Montserrat } from 'next/font/google'
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from '@tanstack/react-query'


const inter = Montserrat({ subsets: ['latin'] ,weight : '700'})

export const metadata: Metadata = {
  title: 'izapteki',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={new QueryClient}>
        <Provider store={store}>
          <BrowserRouter>
          {children}
          </BrowserRouter>
        </Provider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
