'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import {store} from './Store/page'
import { BrowserRouter } from 'react-router-dom';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'izapteki',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <BrowserRouter>
          {children}
          </BrowserRouter>
        </Provider>
      </body>
    </html>
  )
}
